name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Swift Package
        run: swift build --build-tests

      - name: Run Tests
        run: swift test
